/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.Peca;

import Banco.Pecas.Peca;
import Banco.Pecas.PecaDAO;
import Banco.Veiculo.VeiculoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matheusikenaga
 */
public class ConsultaPeca extends javax.swing.JFrame {
    PecaDAO dao = new PecaDAO();
    VeiculoDAO veicDao = new VeiculoDAO();
    
    /**
     * Creates new form ConsultaPeca
     */
    public ConsultaPeca() {
        initComponents();
        AddRowToJTable();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public void AddRowToJTable(){
        
        DefaultTableModel model = new DefaultTableModel();
        Object[] columnsName = new Object [5];
        columnsName[0] = "Código";
        columnsName[1] = "Nome";
        columnsName[2] = "Quantidade";
        columnsName[3] = "Valor";
        columnsName[4] = "Veículo";
        
        model.setColumnIdentifiers(columnsName);
        
        List<Peca> list = dao.selectConsulta();
        
        Object rowData[] = new Object [5];
        for (int i = 0; i < dao.selectConsulta().size();i++) {
            rowData[0] = list.get(i).getCd_peca();
            rowData[1] = list.get(i).getNome_peca();
            rowData[2] = list.get(i).getQtd_peca();
            rowData[3] = list.get(i).getValor_peca();
            rowData[4] = veicDao.selectViagem(list.get(i).getCD_VEIC_PECA()).toString();
            
            model.addRow(rowData);
        }
            jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btEditar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblTitulo.setText("Consulta de Peças");

        DefaultTableModel model = new DefaultTableModel();
        Object[] columnsName = new Object [5];
        columnsName[0] = "Código";
        columnsName[1] = "Nome";
        columnsName[2] = "Quantidade";
        columnsName[3] = "Valor";
        columnsName[4] = "Veículo";

        model.setColumnIdentifiers(columnsName);

        List<Peca> list = dao.selectConsulta();

        Object rowData[] = new Object [5];
        for (int i = 0; i < dao.selectConsulta().size();i++) {
            rowData[0] = list.get(i).getCd_peca();
            rowData[1] = list.get(i).getNome_peca();
            rowData[2] = list.get(i).getQtd_peca();
            rowData[3] = list.get(i).getValor_peca();
            rowData[4] = veicDao.selectViagem(list.get(i).getCD_VEIC_PECA()).toString();

            model.addRow(rowData);
        }
        jTable1.setModel(model);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        btEditar.setText("Editar Registro");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir Registro");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btVoltar)
                        .addGap(24, 24, 24)
                        .addComponent(btEditar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(476, 476, 476))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditar)
                    .addComponent(btVoltar)
                    .addComponent(btExcluir))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed

        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int linhaSelecionadaIndex = jTable1.getSelectedRow();

        Peca pecaAlterar = new Peca();

        pecaAlterar.setCd_peca(Integer.parseInt(model.getValueAt(linhaSelecionadaIndex,0).toString()));
        pecaAlterar.setNome_peca(model.getValueAt(linhaSelecionadaIndex,1).toString());
        pecaAlterar.setQtd_peca(Integer.parseInt(model.getValueAt(linhaSelecionadaIndex,2).toString()));
        pecaAlterar.setValor_peca(Float.parseFloat(model.getValueAt(linhaSelecionadaIndex,3).toString()));
        pecaAlterar.setCD_VEIC_PECA(Integer.parseInt(dao.selectPeca(pecaAlterar.getCd_peca(),"CD_VEIC_PECA")));
//.setCD_VEICULO_VIAGEM(Integer.parseInt(dao.selectViagem(viagemalterar.getCD_VIAGEM(),"CD_VEICULO_VIAGEM")));
        new CadastroPeca(pecaAlterar);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btEditarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int botaoDialogo = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog(null,"Você tem certeza? Essa operação pode ser PERMANENTE!","EXCLUIR VEICULO", botaoDialogo);
        if(botaoDialogo == JOptionPane.YES_OPTION){
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            int linhaSelecionadaIndex = jTable1.getSelectedRow();

            Peca pecaExcluir = new Peca();

            pecaExcluir.setCd_peca(Integer.parseInt(model.getValueAt(linhaSelecionadaIndex,0).toString()));
            pecaExcluir.setNome_peca(model.getValueAt(linhaSelecionadaIndex,1).toString());
            pecaExcluir.setQtd_peca(Integer.parseInt(model.getValueAt(linhaSelecionadaIndex,2).toString()));
            pecaExcluir.setValor_peca(Float.parseFloat(model.getValueAt(linhaSelecionadaIndex,3).toString()));
            pecaExcluir.setCD_VEIC_PECA(Integer.parseInt(model.getValueAt(linhaSelecionadaIndex,4).toString()));

            dao.delete(pecaExcluir);
            this.dispose();
            new ConsultaPeca().setVisible(true);

        }
        if(botaoDialogo == JOptionPane.NO_OPTION){
            remove(botaoDialogo);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btVoltar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
