/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Telas;

import java.awt.Frame;

/**
 *
 * @author matheusikenaga
 */
public class Modulo1Cadastros extends javax.swing.JFrame {

    /**
     * Creates new form TelaPreCadastro
     */
    public Modulo1Cadastros() {
        initComponents();
        this.setExtendedState(Frame.MAXIMIZED_BOTH);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btConsultAluguel = new javax.swing.JButton();
        btInsMultaSin = new javax.swing.JButton();
        btConsultPecas = new javax.swing.JButton();
        btConsultMotorista = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btInsMotorista = new javax.swing.JButton();
        btInsVeiculo = new javax.swing.JButton();
        btConsultVeiculo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btConsultMultasSin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btInsPecas = new javax.swing.JButton();
        btConsultViagem = new javax.swing.JButton();
        btInsViagem = new javax.swing.JButton();
        btInsAluguel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        painelSuperior1 = new Telas.PainelSuperior();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 720));

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);

        jLabel4.setText("Cadastro Aluguel");

        btConsultAluguel.setText("Consultar");

        btInsMultaSin.setText("Incluir");

        btConsultPecas.setText("Consultar");

        btConsultMotorista.setText("Consultar");
        btConsultMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultMotoristaActionPerformed(evt);
            }
        });

        jLabel6.setText("Cadastro Multas e Sinistros");

        btInsMotorista.setText("Incluir");
        btInsMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsMotoristaActionPerformed(evt);
            }
        });

        btInsVeiculo.setText("Incluir");
        btInsVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsVeiculoActionPerformed(evt);
            }
        });

        btConsultVeiculo.setText("Consultar");
        btConsultVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultVeiculoActionPerformed(evt);
            }
        });

        jLabel2.setText("Cadastro Veículo");

        btConsultMultasSin.setText("Consultar");

        jLabel1.setText("Cadastro Motorista");

        jLabel5.setText("Cadastro Peças");

        btInsPecas.setText("Incluir");
        btInsPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsPecasActionPerformed(evt);
            }
        });

        btConsultViagem.setText("Consultar");

        btInsViagem.setText("Incluir");
        btInsViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsViagemActionPerformed(evt);
            }
        });

        btInsAluguel.setText("Incluir");

        jLabel3.setText("Cadastro Viagem");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(122, 122, 122)
                        .addComponent(btInsMotorista)
                        .addGap(118, 118, 118)
                        .addComponent(btConsultMotorista))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(136, 136, 136)
                        .addComponent(btInsVeiculo)
                        .addGap(118, 118, 118)
                        .addComponent(btConsultVeiculo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3)
                        .addGap(136, 136, 136)
                        .addComponent(btInsViagem)
                        .addGap(118, 118, 118)
                        .addComponent(btConsultViagem))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(136, 136, 136)
                        .addComponent(btInsAluguel)
                        .addGap(118, 118, 118)
                        .addComponent(btConsultAluguel))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(72, 72, 72)
                            .addComponent(btInsMultaSin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btConsultMultasSin))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(149, 149, 149)
                            .addComponent(btInsPecas)
                            .addGap(118, 118, 118)
                            .addComponent(btConsultPecas))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btInsMotorista)
                    .addComponent(btConsultMotorista))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addComponent(btInsVeiculo)
                    .addComponent(btConsultVeiculo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3))
                    .addComponent(btInsViagem)
                    .addComponent(btConsultViagem))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4))
                    .addComponent(btInsAluguel)
                    .addComponent(btConsultAluguel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btInsPecas)
                        .addComponent(jLabel5))
                    .addComponent(btConsultPecas))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6))
                    .addComponent(btInsMultaSin)
                    .addComponent(btConsultMultasSin))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(painelSuperior1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelSuperior1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInsMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsMotoristaActionPerformed
        new CadastroMotorista().setVisible(true);
        //this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btInsMotoristaActionPerformed

    private void btInsVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsVeiculoActionPerformed
        // TODO add your handling code here:
        new CadastroVeiculo().setVisible(true);
        //this.dispose();

    }//GEN-LAST:event_btInsVeiculoActionPerformed

    private void btInsPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsPecasActionPerformed
        new CadastroPeca().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btInsPecasActionPerformed

    private void btInsViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsViagemActionPerformed
        new CadastroViagem().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btInsViagemActionPerformed

    private void btConsultMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultMotoristaActionPerformed
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btConsultMotoristaActionPerformed

    private void btConsultVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultVeiculoActionPerformed
        new ConsultaVeiculo().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btConsultVeiculoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultAluguel;
    private javax.swing.JButton btConsultMotorista;
    private javax.swing.JButton btConsultMultasSin;
    private javax.swing.JButton btConsultPecas;
    private javax.swing.JButton btConsultVeiculo;
    private javax.swing.JButton btConsultViagem;
    private javax.swing.JButton btInsAluguel;
    private javax.swing.JButton btInsMotorista;
    private javax.swing.JButton btInsMultaSin;
    private javax.swing.JButton btInsPecas;
    private javax.swing.JButton btInsVeiculo;
    private javax.swing.JButton btInsViagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private Telas.PainelSuperior painelSuperior1;
    // End of variables declaration//GEN-END:variables
}
