/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.Frame;

/**
 *
 * @author matheusikenaga
 */
public class Modulo5 extends javax.swing.JFrame {

    /**
     * Creates new form Modulo5
     */
    public Modulo5() {
        initComponents();
        this.setExtendedState(Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btGerFrotas = new javax.swing.JButton();
        btEstoque = new javax.swing.JButton();
        btLocação = new javax.swing.JButton();
        btFinancas = new javax.swing.JButton();
        btManut = new javax.swing.JButton();
        btMultasSinist = new javax.swing.JButton();
        btSIGEGFROTAS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btGerFrotas.setIcon(new javax.swing.ImageIcon("/Users/matheusikenaga/NetBeansProjects/SIGEFROTAS/SIGEFROTAS/imgJAVA/ger_frota 89x89.png")); // NOI18N
        btGerFrotas.setBorderPainted(false);
        btGerFrotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerFrotasActionPerformed(evt);
            }
        });

        btEstoque.setText("jButton1");
        btEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEstoqueActionPerformed(evt);
            }
        });

        btLocação.setText("jButton1");
        btLocação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLocaçãoActionPerformed(evt);
            }
        });

        btFinancas.setText("jButton1");
        btFinancas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinancasActionPerformed(evt);
            }
        });

        btManut.setText("jButton1");
        btManut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManutActionPerformed(evt);
            }
        });

        btMultasSinist.setText("jButton1");
        btMultasSinist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMultasSinistActionPerformed(evt);
            }
        });

        btSIGEGFROTAS.setIcon(new javax.swing.ImageIcon("/Users/matheusikenaga/NetBeansProjects/SIGEFROTAS/SIGEFROTAS/imgJAVA/sige logo 88x88.png")); // NOI18N
        btSIGEGFROTAS.setBorderPainted(false);
        btSIGEGFROTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSIGEGFROTASActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btSIGEGFROTAS)
                .addGap(295, 295, 295)
                .addComponent(btGerFrotas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLocação)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFinancas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btManut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMultasSinist)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSIGEGFROTAS, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLocação, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btFinancas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btManut, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMultasSinist, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(btGerFrotas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 613, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGerFrotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerFrotasActionPerformed
        new Modulo1().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btGerFrotasActionPerformed

    private void btEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEstoqueActionPerformed
        new Modulo2().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btEstoqueActionPerformed

    private void btLocaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLocaçãoActionPerformed
        new Modulo3().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btLocaçãoActionPerformed

    private void btFinancasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinancasActionPerformed
        new Modulo4().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btFinancasActionPerformed

    private void btManutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManutActionPerformed
        new Modulo5().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btManutActionPerformed

    private void btMultasSinistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMultasSinistActionPerformed
        new Modulo6().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btMultasSinistActionPerformed

    private void btSIGEGFROTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSIGEGFROTASActionPerformed
        new TelaInicial().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btSIGEGFROTASActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEstoque;
    private javax.swing.JButton btFinancas;
    private javax.swing.JButton btGerFrotas;
    private javax.swing.JButton btLocação;
    private javax.swing.JButton btManut;
    private javax.swing.JButton btMultasSinist;
    private javax.swing.JButton btSIGEGFROTAS;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
