/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.Frame;

/**
 *
 * @author matheusikenaga
 */
public class TelaPreCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaPreCadastro
     */
    public TelaPreCadastro() {
        initComponents();
        this.setExtendedState(Frame.MAXIMIZED_BOTH);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btInsMotorista = new javax.swing.JButton();
        btConsultMotorista = new javax.swing.JButton();
        btInsVeiculo = new javax.swing.JButton();
        btConsultVeiculo = new javax.swing.JButton();
        btInsViagem = new javax.swing.JButton();
        btConsultViagem = new javax.swing.JButton();
        btInsAluguel = new javax.swing.JButton();
        btConsultAluguel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btInsPecas = new javax.swing.JButton();
        btConsultPecas = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btInsMultaSin = new javax.swing.JButton();
        btConsultMultasSin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        btInsMotorista.setText("Incluir");
        btInsMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsMotoristaActionPerformed(evt);
            }
        });

        btConsultMotorista.setText("Consultar");

        btInsVeiculo.setText("Incluir");
        btInsVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsVeiculoActionPerformed(evt);
            }
        });

        btConsultVeiculo.setText("Consultar");

        btInsViagem.setText("Incluir");

        btConsultViagem.setText("Consultar");

        btInsAluguel.setText("Incluir");

        btConsultAluguel.setText("Consultar");

        jLabel1.setText("Cadastro Motorista");

        jLabel2.setText("Cadastro Veículo");

        jLabel3.setText("Cadastro Viagem");

        jLabel4.setText("Cadastro Aluguel");

        jLabel5.setText("Cadastro Peças");

        btInsPecas.setText("Incluir");

        btConsultPecas.setText("Consultar");

        jLabel6.setText("Cadastro Multas e Sinistros");

        btInsMultaSin.setText("Incluir");

        btConsultMultasSin.setText("Consultar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1)
                        .addGap(122, 122, 122)
                        .addComponent(btInsMotorista)
                        .addGap(118, 118, 118)
                        .addComponent(btConsultMotorista))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel2)
                        .addGap(136, 136, 136)
                        .addComponent(btInsVeiculo)
                        .addGap(118, 118, 118)
                        .addComponent(btConsultVeiculo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel3)
                        .addGap(136, 136, 136)
                        .addComponent(btInsViagem)
                        .addGap(118, 118, 118)
                        .addComponent(btConsultViagem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel4)
                        .addGap(136, 136, 136)
                        .addComponent(btInsAluguel)
                        .addGap(118, 118, 118)
                        .addComponent(btConsultAluguel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(72, 72, 72)
                                .addComponent(btInsMultaSin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btConsultMultasSin))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(149, 149, 149)
                                .addComponent(btInsPecas)
                                .addGap(118, 118, 118)
                                .addComponent(btConsultPecas)))))
                .addGap(600, 600, 600))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btInsMotorista)
                    .addComponent(btConsultMotorista))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addComponent(btInsVeiculo)
                    .addComponent(btConsultVeiculo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3))
                    .addComponent(btInsViagem)
                    .addComponent(btConsultViagem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4))
                    .addComponent(btInsAluguel)
                    .addComponent(btConsultAluguel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btInsPecas)
                        .addComponent(jLabel5))
                    .addComponent(btConsultPecas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6))
                    .addComponent(btInsMultaSin)
                    .addComponent(btConsultMultasSin))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInsMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsMotoristaActionPerformed
        new CadastroMotorista().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btInsMotoristaActionPerformed

    private void btInsVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsVeiculoActionPerformed
        // TODO add your handling code here:
        new CadastroVeiculo().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btInsVeiculoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultAluguel;
    private javax.swing.JButton btConsultMotorista;
    private javax.swing.JButton btConsultMultasSin;
    private javax.swing.JButton btConsultPecas;
    private javax.swing.JButton btConsultVeiculo;
    private javax.swing.JButton btConsultViagem;
    private javax.swing.JButton btInsAluguel;
    private javax.swing.JButton btInsMotorista;
    private javax.swing.JButton btInsMultaSin;
    private javax.swing.JButton btInsPecas;
    private javax.swing.JButton btInsVeiculo;
    private javax.swing.JButton btInsViagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
