package Telas.Motorista;

import Banco.Motorista.Motorista;
import Banco.Motorista.MotoristaDAO;
import java.util.Date;
import java.text.DateFormat;

import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.ParseException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 *
 * @author matheusikenaga
 */
public class CadastroMotorista extends javax.swing.JFrame {
    
    private MotoristaDAO dao= new MotoristaDAO();
    private Motorista motorista = new Motorista();
    

    /**
     * Creates new form CadastroMotorista
     */
    public CadastroMotorista() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.lbCodMot.setVisible(false);
        this.tbCodMototista.setVisible(false);
        //this.setExtendedState(Frame.MAXIMIZED_BOTH);
        this.setVisible(true);
        this.cbSexo.setSelectedItem(null);
        this.dcDtNasc.setDateFormatString("dd/MM/yyyy");
        this.dcCnh.setDateFormatString("dd/MM/yyyy");
    }
    

    
    public CadastroMotorista(Motorista motorista){
        initComponents();

        this.setLocationRelativeTo(null);
        
        this.tbCodMototista.setText(Integer.toString(motorista.getCD_MOTORISTA()));
        this.tbNomeCadMot.setText(motorista.getNm_motorista());
        this.tbTelefoneCadMot.setText(motorista.getTELEFONE_motorista());
        this.tbCpfCadMot.setText(motorista.getCpf_motorista());
        this.tbRG.setText(motorista.getRg_motorista());       
        
        //AQUI PASSA A DATA DE NASC PARA JCHOOSEDATE
        
        String dtSet =(motorista.getDT_NASC_MOTORISTA().substring(6,10)+ "-"+
                       motorista.getDT_NASC_MOTORISTA().substring(3,5)+ "-"+
                       motorista.getDT_NASC_MOTORISTA().substring(0,2));
        try {
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dtSet);
            
            this.dcDtNasc.setDate(date);
            this.dcDtNasc.setDateFormatString("dd/MM/yyyy");
        } catch (ParseException ex) {
            Logger.getLogger(CadastroMotorista.class.getName()).log(Level.SEVERE, null, ex);
        }
        //************************************************************************************
                
                
         //AQUI PASSA A DATA DE VAL CNH PARA JCHOOSEDATE       
                
        String dtSetCnh =(motorista.getVAL_CNH_MOTORISTA().substring(6,10)+ "-"+
                       motorista.getVAL_CNH_MOTORISTA().substring(3,5)+ "-"+
                       motorista.getVAL_CNH_MOTORISTA().substring(0,2));
        System.out.println(dtSetCnh);
        try {
            Date dateCnh = new SimpleDateFormat("yyyy-MM-dd").parse(dtSetCnh);
            System.out.println(dateCnh);
            this.dcCnh.setDate(dateCnh);
            this.dcCnh.setDateFormatString("dd/MM/yyyy");
        } catch (ParseException ex) {
            Logger.getLogger(CadastroMotorista.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //************************************************************************************

        
        this.cbSexo.setSelectedItem(motorista.getSX_MOTORISTA());
        this.tbNumCnh.setText(motorista.getCnh_motorista());  
        this.tbObs.setText(motorista.getObs_motorista());
        this.setVisible(true);
    
    
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbCodMototista = new javax.swing.JTextField();
        tbNomeCadMot = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter tel= new javax.swing.text.MaskFormatter("(##)#####-####");
            tbTelefoneCadMot = new javax.swing.JFormattedTextField(tel);
            try{
                javax.swing.text.MaskFormatter cpf= new javax.swing.text.MaskFormatter("###.###.###-##");
                tbCpfCadMot = new javax.swing.JFormattedTextField(cpf);
                try{
                    javax.swing.text.MaskFormatter RG= new javax.swing.text.MaskFormatter("##.###.###-A");
                    tbRG = new javax.swing.JFormattedTextField(RG);
                    try{
                        javax.swing.text.MaskFormatter cnh= new javax.swing.text.MaskFormatter("###########");
                        tbNumCnh = new javax.swing.JFormattedTextField(cnh);
                        lbCodMot = new javax.swing.JLabel();
                        jLabel2 = new javax.swing.JLabel();
                        jLabel3 = new javax.swing.JLabel();
                        jLabel4 = new javax.swing.JLabel();
                        jLabel5 = new javax.swing.JLabel();
                        jLabel6 = new javax.swing.JLabel();
                        jLabel7 = new javax.swing.JLabel();
                        jLabel8 = new javax.swing.JLabel();
                        jLabel9 = new javax.swing.JLabel();
                        cbSexo = new javax.swing.JComboBox<>();
                        jLabel10 = new javax.swing.JLabel();
                        tbObs = new javax.swing.JTextField();
                        jLabel11 = new javax.swing.JLabel();
                        btSave = new javax.swing.JButton();
                        btCanc = new javax.swing.JButton();
                        btLimpar = new javax.swing.JButton();
                        dcDtNasc = new com.toedter.calendar.JDateChooser();
                        dcCnh = new com.toedter.calendar.JDateChooser();

                        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                        tbCodMototista.setEnabled(false);
                        tbCodMototista.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tbCodMototistaActionPerformed(evt);
                            }
                        });

                    }
                    catch (Exception e){
                    }
                    tbTelefoneCadMot.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            tbTelefoneCadMotActionPerformed(evt);
                        }
                    });

                }
                catch (Exception e){
                }

            }
            catch (Exception e){
            }

        }
        catch (Exception e){
        }

        lbCodMot.setText("Código do Motorista");

        jLabel2.setText("Nome");

        jLabel3.setText("Telefone");

        jLabel4.setText(" CPF");

        jLabel5.setText(" RG");

        jLabel6.setText("Data de Nascimento");

        jLabel7.setText("  Número da CNH");

        jLabel8.setText("Vencimento CNH");

        jLabel9.setText("Sexo");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino"}));
        cbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoActionPerformed(evt);
            }
        });

        jLabel10.setText("Observações");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel11.setText("Cadastro de Motoristas");

        btSave.setText("Salvar");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btCanc.setText("Cancelar");
        btCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbCpfCadMot, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(lbCodMot)
                                    .addComponent(tbCodMototista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cbSexo, 0, 278, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbRG)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(tbNumCnh, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(tbNomeCadMot))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 588, Short.MAX_VALUE))
                                    .addComponent(tbTelefoneCadMot)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dcCnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dcDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tbObs)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCanc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSave)))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(lbCodMot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbCodMototista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbNomeCadMot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbTelefoneCadMot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tbCpfCadMot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tbRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dcDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbNumCnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dcCnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbObs, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCanc)
                    .addComponent(btSave)
                    .addComponent(btLimpar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbCodMototistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCodMototistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbCodMototistaActionPerformed

    private void cbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSexoActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        
        // Acao do Botao para limpar todos os campos da tela de cadastro
        this.tbCodMototista.setText("");
        this.tbNomeCadMot.setText("");
        this.tbNumCnh.setText("");
        this.tbCpfCadMot.setText("");
        this.tbRG.setText("");
        this.cbSexo.setSelectedItem(null);
        this.tbObs.setText("");
        this.tbTelefoneCadMot.setText("");
        
    }//GEN-LAST:event_btLimparActionPerformed

    private void btCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        //new TelaPreCadastro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCancActionPerformed

    private void tbTelefoneCadMotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTelefoneCadMotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbTelefoneCadMotActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        
        if(this.tbNomeCadMot.getText().equals("")||
           this.tbTelefoneCadMot.getText().equals("")||
           (this.tbCpfCadMot.getText().equals("   .   .   -  "))||
           this.tbRG.getText().equals("")||
           this.cbSexo.getSelectedItem().equals("")||
           this.tbNumCnh.getText().equals("")||
           this.dcCnh.getDate().equals("")){
            
            JOptionPane.showMessageDialog(null, "Preencha os campos de: Nome, Tel, CPF, RG, Data de Nascimento, Sexo, Num. CNH e Data de Validade da CNH");
            
            
        }else{
        
            if(this.tbCodMototista.getText().isEmpty()){
            
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            motorista.setNm_motorista(this.tbNomeCadMot.getText());
            motorista.setTELEFONE_motorista(this.tbTelefoneCadMot.getText());
            motorista.setCpf_motorista(this.tbCpfCadMot.getText());
            motorista.setRg_motorista(this.tbRG.getText());
            motorista.setDT_NASC_MOTORISTA(df.format(this.dcDtNasc.getDate()));
            motorista.setSX_MOTORISTA(this.cbSexo.getSelectedItem().toString());
            motorista.setCnh_motorista (this.tbNumCnh.getText());
            motorista.setVAL_CNH_MOTORISTA(df.format(this.dcCnh.getDate()));
            motorista.setObs_motorista(this.tbObs.getText());
            dao.insert(motorista);
            this.dispose();
        
            }else if(this.tbCodMototista.getText() != null){
            motorista.setCD_MOTORISTA(Integer.parseInt(this.tbCodMototista.getText()));
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            motorista.setNm_motorista(this.tbNomeCadMot.getText());
            motorista.setTELEFONE_motorista(this.tbTelefoneCadMot.getText());
            motorista.setCpf_motorista(this.tbCpfCadMot.getText());
            motorista.setRg_motorista(this.tbRG.getText());
            motorista.setDT_NASC_MOTORISTA(df.format(this.dcDtNasc.getDate()));
            motorista.setSX_MOTORISTA(this.cbSexo.getSelectedItem().toString());
            motorista.setCnh_motorista (this.tbNumCnh.getText());
            motorista.setVAL_CNH_MOTORISTA(df.format(this.dcCnh.getDate()));
            motorista.setObs_motorista(this.tbObs.getText());
            
            dao.update(motorista);
            new ConsultaMotorista();
            this.dispose();
        }
    }//GEN-LAST:event_btSaveActionPerformed
}
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCanc;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSave;
    private javax.swing.JComboBox<String> cbSexo;
    private com.toedter.calendar.JDateChooser dcCnh;
    private com.toedter.calendar.JDateChooser dcDtNasc;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbCodMot;
    private javax.swing.JTextField tbCodMototista;
    private javax.swing.JTextField tbCpfCadMot;
    private javax.swing.JTextField tbNomeCadMot;
    private javax.swing.JTextField tbNumCnh;
    private javax.swing.JTextField tbObs;
    private javax.swing.JTextField tbRG;
    private javax.swing.JTextField tbTelefoneCadMot;
    // End of variables declaration//GEN-END:variables

    private Object SimpleDateFormat(String ddMMyyyy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
